<?php

namespace Database\Factories;

use App\Models\Event;
use App\Models\ScannerStation;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<ScannerStation>
 */
class ScannerStationFactory extends Factory
{
    public function definition(): array
    {
        // token is generated by the model; organization_id auto-fills from the tenant.
        return [
            'event_id' => Event::factory(),
            'label' => 'Door '.fake()->randomElement(['A', 'B', 'C']),
            'active' => true,
        ];
    }
}
